### ISSUE TITLE
DirtyFieldsModel + defer causes recursion depth issue

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/cityhallmonitor#116]
When using defer on a model that inherits from the `DirtyFieldsModel`, maximum recursion depth is reached, e.g.

```
>>> Document.objects.defer("text").extra(where=[....])
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 138, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 255, in iterator
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/base.py", line 487, in from_db
    new = cls(**dict(zip(field_names, values)))
  File "/Users/jenny/repos/cityhallmonitor/cityhallmonitor/models.py", line 55, in __init__
    self.reset_state()
  File "/Users/jenny/repos/cityhallmonitor/cityhallmonitor/models.py", line 69, in reset_state
    self._original_state = self._as_dict()
  File "/Users/jenny/repos/cityhallmonitor/cityhallmonitor/models.py", line 61, in _as_dict
    field_value = getattr(self, field.name)
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query_utils.py", line 144, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/base.py", line 621, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/query.py", line 255, in iterator
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/Users/jenny/envs/cityhallmonitor/lib/python3.4/site-packages/django/db/models/base.py", line 487, in from_db
    new = cls(**dict(zip(field_names, values)))
  File "/Users/jenny/repos/cityhallmonitor/cityhallmonitor/models.py", line 55, in __init__
    self.reset_state()
  File "/Users/jenny/repos/cityhallmonitor/cityhallmonitor/models.py", line 69, in reset_state
    self._original_state = self._as_dict()
...
```

There is probably a way to fix this.  There are definitely cases where we are only reading data and don't care about tracking the 'dirty' state of an instance.

**Comment by jywsn** [comment]
One solution is to create a proxy model for Document that overrides the `DirtyFieldModel` methods to do nothing (and then use that model for the site search queries).
